apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentms-deployment
  labels:
    app: PaymentMs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PaymentMs  
  template:
    metadata:
      labels:
        app: PaymentMs
    spec:
      containers:
      - name: paymentkr25
        image: paymentkr25.azurecr.io/paymentromsrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: paymentmssvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PaymentMs